trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  nuget_name: nuget-sample
  nuget_server: https://pkgs.dev.azure.com/psbds/azdevops-nuget-artifact-sysuser-auth-sample/_packaging/nuget-sample/nuget/v3/index.json
  nuget_user: nuget-sample
  library: psbds.SampleLibrary
  version: 1.0.$(Build.BuildId)
  packageName: $(library).$(version).nupkg

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
    projects: 'library/**/*.csproj'
    arguments: '-c Release'

- task: DotNetCoreCLI@2
  displayName: 'Pack Project'
  inputs:
    command: 'pack'
    packagesToPack: 'library/**/*.csproj'
    configuration: 'Release'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'version'
    
- task: DotNetCoreCLI@2
  displayName: 'Add Nuget Source'
  inputs:
    command: 'custom'
    custom: 'nuget'
    arguments: 'add source $(nuget_server) -n $(nuget_name) -u $(nuget_name) -p "$(System.AccessToken)" --store-password-in-clear-text'

- task: DotNetCoreCLI@2
  displayName: 'Push to Nuget Source'
  inputs:
    command: 'custom'
    custom: 'nuget'
    arguments: 'push -s $(nuget_name) -k "$(System.AccessToken)" $(Build.ArtifactStagingDirectory)/$(packageName)'